//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_Client.ContabilidadeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrejuizoPeca", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PrejuizoPeca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_PecaField;
        
        private decimal Prejuizo_TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo_Peca {
            get {
                return this.Codigo_PecaField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_PecaField, value) != true)) {
                    this.Codigo_PecaField = value;
                    this.RaisePropertyChanged("Codigo_Peca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Prejuizo_Total {
            get {
                return this.Prejuizo_TotalField;
            }
            set {
                if ((this.Prejuizo_TotalField.Equals(value) != true)) {
                    this.Prejuizo_TotalField = value;
                    this.RaisePropertyChanged("Prejuizo_Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Custos_Peca", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Custos_Peca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_CustoField;
        
        private int ID_ProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_PecaField;
        
        private int Tempo_ProducaoField;
        
        private decimal Custo_ProducaoField;
        
        private decimal PrejuizoField;
        
        private decimal LucroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Custo {
            get {
                return this.ID_CustoField;
            }
            set {
                if ((this.ID_CustoField.Equals(value) != true)) {
                    this.ID_CustoField = value;
                    this.RaisePropertyChanged("ID_Custo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Produto {
            get {
                return this.ID_ProdutoField;
            }
            set {
                if ((this.ID_ProdutoField.Equals(value) != true)) {
                    this.ID_ProdutoField = value;
                    this.RaisePropertyChanged("ID_Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Codigo_Peca {
            get {
                return this.Codigo_PecaField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_PecaField, value) != true)) {
                    this.Codigo_PecaField = value;
                    this.RaisePropertyChanged("Codigo_Peca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Tempo_Producao {
            get {
                return this.Tempo_ProducaoField;
            }
            set {
                if ((this.Tempo_ProducaoField.Equals(value) != true)) {
                    this.Tempo_ProducaoField = value;
                    this.RaisePropertyChanged("Tempo_Producao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Custo_Producao {
            get {
                return this.Custo_ProducaoField;
            }
            set {
                if ((this.Custo_ProducaoField.Equals(value) != true)) {
                    this.Custo_ProducaoField = value;
                    this.RaisePropertyChanged("Custo_Producao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Prejuizo {
            get {
                return this.PrejuizoField;
            }
            set {
                if ((this.PrejuizoField.Equals(value) != true)) {
                    this.PrejuizoField = value;
                    this.RaisePropertyChanged("Prejuizo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal Lucro {
            get {
                return this.LucroField;
            }
            set {
                if ((this.LucroField.Equals(value) != true)) {
                    this.LucroField = value;
                    this.RaisePropertyChanged("Lucro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContabilidadeService.ContabilidadeSoap")]
    public interface ContabilidadeSoap {
        
        // CODEGEN: Generating message contract since element name PecaComMaiorPrejuizoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PecaComMaiorPrejuizo", ReplyAction="*")]
        WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoResponse PecaComMaiorPrejuizo(WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PecaComMaiorPrejuizo", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoResponse> PecaComMaiorPrejuizoAsync(WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterCustoTotal", ReplyAction="*")]
        decimal ObterCustoTotal(System.DateTime inicio, System.DateTime fim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterCustoTotal", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> ObterCustoTotalAsync(System.DateTime inicio, System.DateTime fim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterLucroTotal", ReplyAction="*")]
        decimal ObterLucroTotal(System.DateTime inicio, System.DateTime fim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterLucroTotal", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> ObterLucroTotalAsync(System.DateTime inicio, System.DateTime fim);
        
        // CODEGEN: Generating message contract since element name ObterPrejuizoPorPecaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterPrejuizoPorPeca", ReplyAction="*")]
        WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaResponse ObterPrejuizoPorPeca(WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterPrejuizoPorPeca", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaResponse> ObterPrejuizoPorPecaAsync(WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequest request);
        
        // CODEGEN: Generating message contract since element name codigoPeca from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterDadosPorPeca", ReplyAction="*")]
        WebService_Client.ContabilidadeService.ObterDadosPorPecaResponse ObterDadosPorPeca(WebService_Client.ContabilidadeService.ObterDadosPorPecaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterDadosPorPeca", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService_Client.ContabilidadeService.ObterDadosPorPecaResponse> ObterDadosPorPecaAsync(WebService_Client.ContabilidadeService.ObterDadosPorPecaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PecaComMaiorPrejuizoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PecaComMaiorPrejuizo", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequestBody Body;
        
        public PecaComMaiorPrejuizoRequest() {
        }
        
        public PecaComMaiorPrejuizoRequest(WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PecaComMaiorPrejuizoRequestBody {
        
        public PecaComMaiorPrejuizoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PecaComMaiorPrejuizoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PecaComMaiorPrejuizoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoResponseBody Body;
        
        public PecaComMaiorPrejuizoResponse() {
        }
        
        public PecaComMaiorPrejuizoResponse(WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PecaComMaiorPrejuizoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PecaComMaiorPrejuizoResult;
        
        public PecaComMaiorPrejuizoResponseBody() {
        }
        
        public PecaComMaiorPrejuizoResponseBody(string PecaComMaiorPrejuizoResult) {
            this.PecaComMaiorPrejuizoResult = PecaComMaiorPrejuizoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterPrejuizoPorPecaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterPrejuizoPorPeca", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequestBody Body;
        
        public ObterPrejuizoPorPecaRequest() {
        }
        
        public ObterPrejuizoPorPecaRequest(WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterPrejuizoPorPecaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime inicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fim;
        
        public ObterPrejuizoPorPecaRequestBody() {
        }
        
        public ObterPrejuizoPorPecaRequestBody(System.DateTime inicio, System.DateTime fim) {
            this.inicio = inicio;
            this.fim = fim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterPrejuizoPorPecaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterPrejuizoPorPecaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaResponseBody Body;
        
        public ObterPrejuizoPorPecaResponse() {
        }
        
        public ObterPrejuizoPorPecaResponse(WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterPrejuizoPorPecaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService_Client.ContabilidadeService.PrejuizoPeca[] ObterPrejuizoPorPecaResult;
        
        public ObterPrejuizoPorPecaResponseBody() {
        }
        
        public ObterPrejuizoPorPecaResponseBody(WebService_Client.ContabilidadeService.PrejuizoPeca[] ObterPrejuizoPorPecaResult) {
            this.ObterPrejuizoPorPecaResult = ObterPrejuizoPorPecaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterDadosPorPecaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterDadosPorPeca", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Client.ContabilidadeService.ObterDadosPorPecaRequestBody Body;
        
        public ObterDadosPorPecaRequest() {
        }
        
        public ObterDadosPorPecaRequest(WebService_Client.ContabilidadeService.ObterDadosPorPecaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterDadosPorPecaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigoPeca;
        
        public ObterDadosPorPecaRequestBody() {
        }
        
        public ObterDadosPorPecaRequestBody(string codigoPeca) {
            this.codigoPeca = codigoPeca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterDadosPorPecaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterDadosPorPecaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Client.ContabilidadeService.ObterDadosPorPecaResponseBody Body;
        
        public ObterDadosPorPecaResponse() {
        }
        
        public ObterDadosPorPecaResponse(WebService_Client.ContabilidadeService.ObterDadosPorPecaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterDadosPorPecaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService_Client.ContabilidadeService.Custos_Peca ObterDadosPorPecaResult;
        
        public ObterDadosPorPecaResponseBody() {
        }
        
        public ObterDadosPorPecaResponseBody(WebService_Client.ContabilidadeService.Custos_Peca ObterDadosPorPecaResult) {
            this.ObterDadosPorPecaResult = ObterDadosPorPecaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContabilidadeSoapChannel : WebService_Client.ContabilidadeService.ContabilidadeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContabilidadeSoapClient : System.ServiceModel.ClientBase<WebService_Client.ContabilidadeService.ContabilidadeSoap>, WebService_Client.ContabilidadeService.ContabilidadeSoap {
        
        public ContabilidadeSoapClient() {
        }
        
        public ContabilidadeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContabilidadeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContabilidadeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContabilidadeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoResponse WebService_Client.ContabilidadeService.ContabilidadeSoap.PecaComMaiorPrejuizo(WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequest request) {
            return base.Channel.PecaComMaiorPrejuizo(request);
        }
        
        public string PecaComMaiorPrejuizo() {
            WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequest inValue = new WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequest();
            inValue.Body = new WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequestBody();
            WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoResponse retVal = ((WebService_Client.ContabilidadeService.ContabilidadeSoap)(this)).PecaComMaiorPrejuizo(inValue);
            return retVal.Body.PecaComMaiorPrejuizoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoResponse> WebService_Client.ContabilidadeService.ContabilidadeSoap.PecaComMaiorPrejuizoAsync(WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequest request) {
            return base.Channel.PecaComMaiorPrejuizoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoResponse> PecaComMaiorPrejuizoAsync() {
            WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequest inValue = new WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequest();
            inValue.Body = new WebService_Client.ContabilidadeService.PecaComMaiorPrejuizoRequestBody();
            return ((WebService_Client.ContabilidadeService.ContabilidadeSoap)(this)).PecaComMaiorPrejuizoAsync(inValue);
        }
        
        public decimal ObterCustoTotal(System.DateTime inicio, System.DateTime fim) {
            return base.Channel.ObterCustoTotal(inicio, fim);
        }
        
        public System.Threading.Tasks.Task<decimal> ObterCustoTotalAsync(System.DateTime inicio, System.DateTime fim) {
            return base.Channel.ObterCustoTotalAsync(inicio, fim);
        }
        
        public decimal ObterLucroTotal(System.DateTime inicio, System.DateTime fim) {
            return base.Channel.ObterLucroTotal(inicio, fim);
        }
        
        public System.Threading.Tasks.Task<decimal> ObterLucroTotalAsync(System.DateTime inicio, System.DateTime fim) {
            return base.Channel.ObterLucroTotalAsync(inicio, fim);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaResponse WebService_Client.ContabilidadeService.ContabilidadeSoap.ObterPrejuizoPorPeca(WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequest request) {
            return base.Channel.ObterPrejuizoPorPeca(request);
        }
        
        public WebService_Client.ContabilidadeService.PrejuizoPeca[] ObterPrejuizoPorPeca(System.DateTime inicio, System.DateTime fim) {
            WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequest inValue = new WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequest();
            inValue.Body = new WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequestBody();
            inValue.Body.inicio = inicio;
            inValue.Body.fim = fim;
            WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaResponse retVal = ((WebService_Client.ContabilidadeService.ContabilidadeSoap)(this)).ObterPrejuizoPorPeca(inValue);
            return retVal.Body.ObterPrejuizoPorPecaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaResponse> WebService_Client.ContabilidadeService.ContabilidadeSoap.ObterPrejuizoPorPecaAsync(WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequest request) {
            return base.Channel.ObterPrejuizoPorPecaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaResponse> ObterPrejuizoPorPecaAsync(System.DateTime inicio, System.DateTime fim) {
            WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequest inValue = new WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequest();
            inValue.Body = new WebService_Client.ContabilidadeService.ObterPrejuizoPorPecaRequestBody();
            inValue.Body.inicio = inicio;
            inValue.Body.fim = fim;
            return ((WebService_Client.ContabilidadeService.ContabilidadeSoap)(this)).ObterPrejuizoPorPecaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_Client.ContabilidadeService.ObterDadosPorPecaResponse WebService_Client.ContabilidadeService.ContabilidadeSoap.ObterDadosPorPeca(WebService_Client.ContabilidadeService.ObterDadosPorPecaRequest request) {
            return base.Channel.ObterDadosPorPeca(request);
        }
        
        public WebService_Client.ContabilidadeService.Custos_Peca ObterDadosPorPeca(string codigoPeca) {
            WebService_Client.ContabilidadeService.ObterDadosPorPecaRequest inValue = new WebService_Client.ContabilidadeService.ObterDadosPorPecaRequest();
            inValue.Body = new WebService_Client.ContabilidadeService.ObterDadosPorPecaRequestBody();
            inValue.Body.codigoPeca = codigoPeca;
            WebService_Client.ContabilidadeService.ObterDadosPorPecaResponse retVal = ((WebService_Client.ContabilidadeService.ContabilidadeSoap)(this)).ObterDadosPorPeca(inValue);
            return retVal.Body.ObterDadosPorPecaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService_Client.ContabilidadeService.ObterDadosPorPecaResponse> WebService_Client.ContabilidadeService.ContabilidadeSoap.ObterDadosPorPecaAsync(WebService_Client.ContabilidadeService.ObterDadosPorPecaRequest request) {
            return base.Channel.ObterDadosPorPecaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService_Client.ContabilidadeService.ObterDadosPorPecaResponse> ObterDadosPorPecaAsync(string codigoPeca) {
            WebService_Client.ContabilidadeService.ObterDadosPorPecaRequest inValue = new WebService_Client.ContabilidadeService.ObterDadosPorPecaRequest();
            inValue.Body = new WebService_Client.ContabilidadeService.ObterDadosPorPecaRequestBody();
            inValue.Body.codigoPeca = codigoPeca;
            return ((WebService_Client.ContabilidadeService.ContabilidadeSoap)(this)).ObterDadosPorPecaAsync(inValue);
        }
    }
}
